spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.try_gpt4_1: DEBUG
    org.mybatis: DEBUG
    org.springdoc: WARN
    springfox: WARN
    org.springframework.data: WARN
