spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.try_3_7_sonnet
  mapper-scan-package: com.example.try_3_7_sonnet.**.repository

logging:
  level:
    com.example.try_3_7_sonnet: DEBUG
    org.mybatis: DEBUG
    org.springdoc: WARN
    springfox: WARN
    org.springframework.data: WARN
